import React from 'react';

export interface AiProvenanceDotProps {
  provider?: string | null;
  className?: string;
}

/**
 * AiProvenanceDot
 * 
 * Renders a small blue provenance indicator (6-8px diameter) at the top-right corner
 * of cards containing content that was ACTUALLY generated by Ollama.
 * 
 * Provenance Policy:
 * - Blue dot = this specific displayed content was generated by Ollama (ai_provider === 'ollama').
 * - No dot   = fallback/deterministic content (ai_provider === 'fallback' or unanalyzed).
 * 
 * Provenance is determined strictly via backend generation pipeline metadata,
 * NEVER by inspecting response text or checking whether Ollama is online.
 */
export const AiProvenanceDot: React.FC<AiProvenanceDotProps> = ({
  provider,
  className = ''
}) => {
  if (provider !== 'ollama') {
    return null;
  }

  return (
    <span
      className={`inline-block w-2 h-2 rounded-full bg-blue-500 shadow-[0_0_10px_rgba(59,130,246,0.95)] ring-2 ring-blue-400/50 shrink-0 transition-all duration-200 pointer-events-auto cursor-help ${className}`}
      title="Generated by Ollama"
      aria-label="Generated by Ollama"
      role="status"
      data-testid="ai-provenance-dot"
    />
  );
};
