import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const srcDir = path.resolve(__dirname, '../src');

/**
 * Regression Test Suite: KAVACH 6.0 AI Generation Provenance Indicator
 * 
 * Requirements:
 * 1. Provenance is determined strictly via backend generation metadata (ai_provider: 'ollama' vs 'fallback').
 * 2. Small blue dot (6-8px, blue-500, tooltip 'Generated by Ollama') is shown ONLY when ai_provider === 'ollama'.
 * 3. Fallback / deterministic responses (ai_provider === 'fallback') DO NOT display the blue dot.
 * 4. Finding Page AI ANALYSIS card, Finding Detail Security Hypothesis GlassCard, and AiAnalysisPage integrate the indicator.
 */

test('1. AiProvenanceDot component exists and adheres to provenance contract', () => {
  const compPath = path.join(srcDir, 'components/common/AiProvenanceDot.tsx');
  assert.ok(fs.existsSync(compPath), 'AiProvenanceDot.tsx must exist');

  const content = fs.readFileSync(compPath, 'utf-8');

  // Verify it only renders for 'ollama'
  assert.match(content, /provider\s*!==\s*['"]ollama['"]/, 'Must return null unless provider === "ollama"');
  assert.match(content, /title=["']Generated by Ollama["']/, 'Must include title="Generated by Ollama"');
  assert.match(content, /aria-label=["']Generated by Ollama["']/, 'Must include aria-label="Generated by Ollama"');
  assert.match(content, /bg-blue-500/, 'Must use blue color class');
  assert.match(content, /w-2\s+h-2/, 'Must be approximately 6-8px (w-2 h-2)');
});

test('2. GlassCard.tsx supports aiProvider and renders AiProvenanceDot in top-right corner', () => {
  const glassCardPath = path.join(srcDir, 'components/common/GlassCard.tsx');
  const content = fs.readFileSync(glassCardPath, 'utf-8');

  assert.match(content, /aiProvider\?: string/, 'GlassCardProps must declare aiProvider');
  assert.match(content, /AiProvenanceDot/, 'GlassCard must import and render AiProvenanceDot');
  assert.match(content, /aiProvider\s*===\s*['"]ollama['"]/, 'GlassCard must check aiProvider === "ollama"');
  assert.match(content, /absolute top-4 right-4/, 'Indicator must be positioned at top-right corner inside the card');
});

test('3. FindingDetailPage.tsx propagates finding.ai_provider to Security Hypothesis GlassCard', () => {
  const detailPath = path.join(srcDir, 'pages/FindingDetailPage.tsx');
  const content = fs.readFileSync(detailPath, 'utf-8');

  assert.match(content, /title="Security Hypothesis"/, 'Security Hypothesis GlassCard must exist');
  assert.match(content, /aiProvider=\{finding\.ai_provider\}/, 'Must pass finding.ai_provider to Security Hypothesis GlassCard');
});

test('4. EvidenceValidationPage.tsx renders AiProvenanceDot on Stage 5 AI ANALYSIS card', () => {
  const evPath = path.join(srcDir, 'pages/EvidenceValidationPage.tsx');
  const content = fs.readFileSync(evPath, 'utf-8');

  assert.match(content, /✦ AI ANALYSIS/, 'Stage 5 AI ANALYSIS card must exist');
  assert.match(content, /selectedFinding\.ai_provider\s*===\s*['"]ollama['"]/, 'Must check selectedFinding.ai_provider === "ollama"');
  assert.match(content, /AiProvenanceDot\s+provider=\{selectedFinding\.ai_provider\}/, 'Must render AiProvenanceDot with selectedFinding.ai_provider');
});

test('5. AiAnalysisPage.tsx renders AiProvenanceDot when activeResult.ai_provider === "ollama"', () => {
  const aiPagePath = path.join(srcDir, 'pages/AiAnalysisPage.tsx');
  const content = fs.readFileSync(aiPagePath, 'utf-8');

  assert.match(content, /activeResult\.ai_provider\s*===\s*['"]ollama['"]/, 'Must check activeResult.ai_provider === "ollama"');
  assert.match(content, /AiProvenanceDot\s+provider=\{activeResult\.ai_provider\}/, 'Must render AiProvenanceDot on activeResult');
});

test('6. TypeScript definitions include ai_provider on Finding, StructuredAiExplanation, and RagResponse', () => {
  const typesPath = path.join(srcDir, 'types/index.ts');
  const content = fs.readFileSync(typesPath, 'utf-8');

  assert.match(content, /ai_provider\?:\s*['"]ollama['"]\s*\|\s*['"]fallback['"]/, 'Finding and StructuredAiExplanation must include ai_provider in types');
  assert.match(content, /ai_provider\?:\s*['"]ollama['"]/, 'RagResponse must include ai_provider');
});

test('7. FindingDetailPage.tsx passes aiProvider to Recommended Validation GlassCard', () => {
  const detailPath = path.join(srcDir, 'pages/FindingDetailPage.tsx');
  const content = fs.readFileSync(detailPath, 'utf-8');

  assert.match(content, /title="Recommended Validation"[\s\S]*?aiProvider=\{finding\.ai_provider\}/, 'Must pass finding.ai_provider to Recommended Validation GlassCard');
});

test('8. SecurityReportPage.tsx displays AiProvenanceDot for Ollama-generated findings and hypotheses', () => {
  const reportPath = path.join(srcDir, 'pages/SecurityReportPage.tsx');
  const content = fs.readFileSync(reportPath, 'utf-8');

  assert.match(content, /import\s+\{\s*AiProvenanceDot\s*\}\s+from\s+['"]\.\.\/components\/common\/AiProvenanceDot['"]/, 'Must import AiProvenanceDot');
  assert.match(content, /f\.ai_provider\s*===\s*['"]ollama['"][\s\S]*?<AiProvenanceDot provider=\{f\.ai_provider\}/, 'Must render AiProvenanceDot for finding cards with Ollama content');
  assert.match(content, /report-hypothesis-provenance/, 'Must include testid for hypothesis provenance');
});

test('9. AiAnalysisPage.tsx includes provenance banners across risk, remediation, and audit functions', () => {
  const aiPagePath = path.join(srcDir, 'pages/AiAnalysisPage.tsx');
  const content = fs.readFileSync(aiPagePath, 'utf-8');

  assert.match(content, /riskData\.ai_provider\s*===\s*['"]ollama['"]/, 'Must check riskData.ai_provider === "ollama"');
  assert.match(content, /remediationData\.ai_provider\s*===\s*['"]ollama['"]/, 'Must check remediationData.ai_provider === "ollama"');
  assert.match(content, /auditSummaryData\.ai_provider\s*===\s*['"]ollama['"]/, 'Must check auditSummaryData.ai_provider === "ollama"');
});

test('10. Global Provenance Contract: Scenarios A-H evaluation logic', () => {
  // Pure evaluator implementing Step 71 CORE RULE:
  // if ANY visible content block in a card is Ollama-generated -> card provider is 'ollama' (BLUE DOT)
  // otherwise -> 'fallback' (NO DOT)
  function resolveCardProvider(blocks) {
    const hasOllama = blocks.some(b => b.provider === 'ollama');
    return hasOllama ? 'ollama' : 'fallback';
  }

  // A. Entire card generated by Ollama -> blue dot
  const scenarioA = [{ type: 'ai_explanation', provider: 'ollama' }];
  assert.equal(resolveCardProvider(scenarioA), 'ollama');

  // B. One sentence generated by Ollama -> blue dot
  const scenarioB = [
    { type: 'static_header', provider: undefined },
    { type: 'ai_sentence', provider: 'ollama' }
  ];
  assert.equal(resolveCardProvider(scenarioB), 'ollama');

  // C. Mixed deterministic + Ollama content -> blue dot
  const scenarioC = [
    { type: 'deterministic_score', provider: 'fallback' },
    { type: 'ollama_hypothesis', provider: 'ollama' },
    { type: 'database_evidence', provider: undefined }
  ];
  assert.equal(resolveCardProvider(scenarioC), 'ollama');

  // D. Entire card generated by fallback -> no dot
  const scenarioD = [{ type: 'fallback_summary', provider: 'fallback' }];
  assert.equal(resolveCardProvider(scenarioD), 'fallback');

  // E. Ollama online but content not generated by Ollama -> no dot
  // (e.g. system status online, but finding analysis came from rule engine)
  const isOllamaOnline = true;
  const contentProvider = 'fallback'; // content was NOT generated by Ollama
  // Provenance must NEVER be inferred from online status
  assert.notEqual(contentProvider, isOllamaOnline ? 'ollama' : 'fallback');
  assert.equal(contentProvider, 'fallback');

  // F. Ollama unavailable -> fallback/no dot
  const scenarioF = [{ type: 'rule_fallback', provider: 'fallback' }];
  assert.equal(resolveCardProvider(scenarioF), 'fallback');

  // G & H. Multiple cards on same page:
  // Card A contains Ollama content -> dot
  // Card B contains only deterministic content -> no dot
  const pageCardA = [{ type: 'ollama_thesis', provider: 'ollama' }];
  const pageCardB = [{ type: 'raw_evidence_hash', provider: undefined }, { type: 'cwe_title', provider: undefined }];

  assert.equal(resolveCardProvider(pageCardA), 'ollama', 'Card A must receive blue dot');
  assert.equal(resolveCardProvider(pageCardB), 'fallback', 'Card B must NOT receive blue dot');
});

test('11. Deterministic and raw evidence cards intentionally DO NOT display AiProvenanceDot', () => {
  const riskPath = path.join(srcDir, 'pages/RiskPrioritizationPage.tsx');
  const remPath = path.join(srcDir, 'pages/RemediationCenterPage.tsx');

  const riskContent = fs.readFileSync(riskPath, 'utf-8');
  const remContent = fs.readFileSync(remPath, 'utf-8');

  // RiskPrioritizationPage is 100% deterministic formula - must NOT import or render AiProvenanceDot
  assert.ok(!riskContent.includes('AiProvenanceDot'), 'RiskPrioritizationPage must not show AiProvenanceDot');

  // RemediationCenterPage uses rule template logic - must NOT show AiProvenanceDot
  assert.ok(!remContent.includes('AiProvenanceDot'), 'RemediationCenterPage must not show AiProvenanceDot');
});
